version: "3.7"

services:
  paymail:
    container_name: paymail
    image: local.paymail
    environment:
      DOMAIN_TLD: "nchain.com"
      PAYMAIL_HOST: "paymail"
      PAYMAIL_PORT: "8446"
      LOG_LEVEL: "info"
      PAYD_HOST: "payd"
      PAYD_PORT: ":8443"
      TRANSPORT_MODE: "rest"
    ports:
      - "8446:8446"
    networks:
      - regtest-stack

networks:
  regtest-stack:
    external: true
    name: regtest-stack
