version: "3.7"

services:
  paymail:
    container_name: paymail
    image: local.paymail
    build:
      context: .
    environment:
      DOMAIN_TLD: "nchain.com"
      PAYMAIL_DOMAIN: "localhost"
      PAYMAIL_HOST: "paymail"
      PAYMAIL_PORT: "8446"
      LOG_LEVEL: "debug"
      PAYD_HOST: "payd"
      PAYD_PORT: ":8443"
      TRANSPORT_MODE: "http"
    ports:
      - "8446:8446"
    networks:
      - regtest-stack

volumes:
  payd-data:
    external: false

networks:
  regtest-stack:
    external: true
    name: regtest-stack
