version: "3.7"

services:
  p4:
    container_name: p4
    image: local.p4
    environment:
      LOG_LEVEL: "info"
      TRANSPORT_MODE: 'hybrid'
    ports:
      - "8445:8445"
    networks:
      - regtest-stack

  p4-merchant:
    container_name: p4-merchant
    image: local.p4
    environment:
      LOG_LEVEL: "info"
      PAYD_HOST: "payd-merchant"
      PAYD_PORT: ":28443"
      TRANSPORT_MODE: 'hybrid'
      SERVER_HOST: "p4"
      SERVER_PORT: ":28445"
    ports:
      - "28445:28445"
    networks:
      - regtest-stack

networks:
  regtest-stack:
    external: true
    name: regtest-stack
