version: "3.7"

services:
  paymail:
    container_name: paymail
    image: local.paymail
    environment:
      DB_DSN: "file:paydb/paymail.db?cache=shared&_foreign_keys=true"
      DB_SCHEMA_PATH: "migrations/paymail"
      DB_TYPE: "sqlite"
      DOMAIN_TLD: "nchain.com"
      PAYMAIL_ROOT: "http://localhost:8446"
      PAYMAIL_HOST: "paymail"
      PAYMAIL_PORT: "8446"
      LOG_LEVEL: "debug"
      PAYD_HOST: "payd"
      PAYD_PORT: ":8443"
      TRANSPORT_MODE: "http"
    volumes:
      - payd-data:/paydb
    ports:
      - "8446:8446"
    networks:
      - regtest-stack

volumes:
  payd-data:
    external: false

networks:
  regtest-stack:
    external: true
    name: regtest-stack
