version: '3.7'

services:
  paymail:
    container_name: paymail
    image: paymail.service
    build:
      context: .
    env_file:
      - environments/compose.env
    ports:
      - "4000"
    restart: unless-stopped
    networks:
      - platform-services-network

networks:
  platform-services-network:
    external: true