host: localhost:8445
info:
  contact: {}
  description: Payment Protocol Server is an implementation of a Bip-270 payment flow.
  license:
    name: ISC
    url: https://github.com/libsv/go-payment_protocol/blob/master/LICENSE
  termsOfService: https://github.com/libsv/go-payment_protocol/blob/master/CODE_STANDARDS.md
  title: Payment Protocol Server
  version: 0.0.1
paths: {}
swagger: "2.0"
